version: 0.2

env:
  variables:
    REGION: ap-south-1
    REPO_NAME: ui-app
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGISTRY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - REPO_URI=$REGISTRY_URI/$REPO_NAME
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing deployment files...
      - printf '[{\"name\":\"ui-app\",\"imageUri\":\"%s\"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - imagedefinitions.json
